<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/2022_10_03_%EC%84%B8%EC%85%98%20%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1

## 데이터 다운로드
--- 
아래 셀을 실행시켜 데이터를 colab에 불러옵니다.  
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [9]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3gLj0Q6'

import zipfile
with zipfile.ZipFile('3gLj0Q6', 'r') as existing_zip:
    existing_zip.extractall('data')

--2022-10-03 09:33:05--  https://bit.ly/3gLj0Q6
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E [following]
--2022-10-03 09:33:05--  https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E
Resolving drive.google.com (drive.google.com)... 173.194.202.102, 173.194.202.101, 173.194.202.100, ...
Connecting to drive.google.com (drive.google.com)|173.194.202.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/kb0bon02g5oibkjbu8avnfuk6rvkmlk5/1664789550000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download&uuid=011f2f45-d160-4b81-a388-fc32e7910b0b [following]
Warning: wildcards not supported in HTTP.
--2022-10-03 09:33:05--  https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/kb0bon02g5oibkjbu8avnfuk6rvkmlk5/1664789550000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download&uuid=011f2f45-d160-4b81-a388-fc32e7910b0b
Resolving doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)... 142.250.107.132, 2607:f8b0:400e:c0d::84
Connecting to doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)|142.250.107.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39208 (38K) [application/zip]
Saving to: ‘3gLj0Q6.1’

3gLj0Q6.1           100%[===================>]  38.29K  --.-KB/s    in 0.002s

2022-10-03 09:33:06 (23.1 MB/s) - ‘3gLj0Q6.1’ saved [39208/39208]

## 라이브러리 불러오기
---
아래 셀을 실행시켜 pandas 와 DecisionTreeRegressor 를 불러옵니다.

In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

## 데이터 불러오기
---
아래 셀을 실행시켜 csv 파일 데이터를 DataFrame 객체로 불러옵니다.

In [11]:
train = pd.read_csv('data/train.csv') 
test = pd.read_csv('data/test.csv')

## 결측치 제거하기
---
결측치를 제거하고, 결측치가 모두 제거됐는지 확인합니다.

In [12]:
test = test.dropna()
train = train.dropna()

print(train.isnull().sum())

id                        0
hour                      0
hour_bef_temperature      0
hour_bef_precipitation    0
hour_bef_windspeed        0
hour_bef_humidity         0
hour_bef_visibility       0
hour_bef_ozone            0
hour_bef_pm10             0
hour_bef_pm2.5            0
count                     0
dtype: int64

In [13]:
test

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5
0,0,7,20.7,0.0,1.3,62.0,954.0,0.041,44.0,27.0
1,1,17,30.0,0.0,5.4,33.0,1590.0,0.061,49.0,36.0
2,2,13,19.0,1.0,2.1,95.0,193.0,0.020,36.0,28.0
3,4,6,22.5,0.0,2.5,60.0,1185.0,0.027,52.0,38.0
4,5,22,14.6,1.0,3.4,93.0,218.0,0.041,18.0,15.0
...,...,...,...,...,...,...,...,...,...,...
708,2146,3,21.6,0.0,2.6,41.0,2000.0,0.044,25.0,16.0
709,2147,18,24.3,0.0,4.1,46.0,1246.0,0.063,35.0,28.0
712,2165,9,23.3,0.0,2.3,66.0,1789.0,0.020,17.0,15.0
713,2166,16,27.0,0.0,1.6,46.0,1956.0,0.032,40.0,26.0
714,2177,8,22.3,0.0,1.0,63.0,1277.0,0.007,30.0,24.0

In [14]:
train

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,8,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,9,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0
...,...,...,...,...,...,...,...,...,...,...,...
1454,2174,4,16.8,0.0,1.6,53.0,2000.0,0.031,37.0,27.0,21.0
1455,2175,3,10.8,0.0,3.8,45.0,2000.0,0.039,34.0,19.0,20.0
1456,2176,5,18.3,0.0,1.9,54.0,2000.0,0.009,30.0,21.0,22.0
1457,2178,21,20.7,0.0,3.7,37.0,1395.0,0.082,71.0,36.0,216.0
1458,2179,17,21.1,0.0,3.1,47.0,1973.0,0.046,38.0,17.0,170.0

1. train 데이터중 <br>
(1) 예측해야할 `count` 피쳐를 drop()함수를 사용하고, axis=1 옵션을 사용해 해당 열을 제외한 데이터들을 `X_train` 이라는 이름의 DataFrame 객체로 만들고 <br>
(2) `count` 피쳐만을 데이터로 갖는 `Y_train` 이라는 이름의 DataFrame 객체로 만드는 코드를 아래에 작성하세요

In [16]:
X_train=train.drop(['count'], axis=1)

In [18]:
Y_train=train['count']

2. `model` 변수명으로 모델을 선언하고, fit() 함수를 사용해서, `X_train` 을 input 으로 삼고, `Y_train` 을 output 으로 삼아 모델을 훈련시키는 코드를 아래에 작성하세요

In [20]:
model=DecisionTreeRegressor()
model.fit(X_train, Y_train)

DecisionTreeRegressor()

3. predict() 를 이용해 test data 를 훈련된 모델로 예측한 data 를 생성하고 예측결과 상위 5개를 출력하는 코드를 작성하세요.

In [21]:
pred=model.predict(test)

In [23]:
pred[:5]

array([117., 164.,  88.,  49.,  64.])

# Exercise 2

## 데이터 다운로드
---
아래 셀을 실행시켜 데이터를 colab 에 불러옵니다.
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [24]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2022-10-03 09:37:32--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2022-10-03 09:37:32--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 74.125.142.139, 74.125.142.113, 74.125.142.102, ...
Connecting to drive.google.com (drive.google.com)|74.125.142.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/154dd4u5n0d9t0oun06h6vagp24qs9df/1664789850000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=44b15f67-5a50-496a-bcbf-c1dbf1d89a41 [following]
Warning: wildcards not supported in HTTP.
--2022-10-03 09:37:33--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/154dd4u5n0d9t0oun06h6vagp24qs9df/1664789850000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=44b15f67-5a50-496a-bcbf-c1dbf1d89a41
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 142.250.107.132, 2607:f8b0:400e:c0d::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|142.250.107.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‘3i4n1QB.1’

3i4n1QB.1           100%[===================>] 134.47K  --.-KB/s    in 0.002s

2022-10-03 09:37:33 (80.2 MB/s) - ‘3i4n1QB.1’ saved [137694/137694]

In [25]:
# 라이브러리 불러오기

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [26]:
train = pd.read_csv('data/train.csv')

# Scailing
scaler = MinMaxScaler()
scaler.fit(train[['fixed acidity']])
train['Scaled fixed acidity'] = scaler.transform(train[['fixed acidity']])

# Encoding
encoder = OneHotEncoder()
encoder.fit(train[['type']])
onehot = encoder.transform(train[['type']])
onehot = onehot.toarray()
onehot = pd.DataFrame(onehot)
onehot.columns = encoder.get_feature_names()
train = pd.concat([train, onehot], axis = 1)
train = train.drop(columns = ['type'])
train.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Scaled fixed acidity,x0_red,x0_white
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,0.148760,0.0,1.0
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,0.413223,1.0,0.0
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,0.338843,0.0,1.0
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,0.264463,0.0,1.0
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,0.330579,0.0,1.0

4. sklearn에 model_selection 모듈에서 KFold를 불러와보세요

In [27]:
from sklearn.model_selection import KFold

5. KFold에 n_splits = 5, shuffle = True, random_state = 0이라는 인자를 추가해 "kf"라는 변수에 저장해보세요

In [28]:
kf=KFold(n_splits=5, shuffle=True, random_state=0)

6. 반복문을 통해서 1번부터 5번까지의 데이터에 접근해보세요

In [36]:
n_iter=0

for train_idx, valid_idx in kf.split(train):
  train_data=train.iloc[train_idx]
  valid_data=train.iloc[valid_idx]
  n_iter+=1
  print('#{0}번 교차검증 train 데이터: {1}'.format(n_iter, train_data))
  print('#{0}번 교차검증 valid 데이터: {1}'.format(n_iter, valid_data))

#1번 교차검증 train 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
0         0        5            5.6             0.695         0.06
1         1        5            8.8             0.610         0.14
2         2        5            7.9             0.210         0.39
3         3        6            7.0             0.210         0.31
5         5        6            6.0             0.190         0.37
...     ...      ...            ...               ...          ...
5491   5491        7            6.9             0.340         0.30
5492   5492        5            7.7             0.150         0.29
5494   5494        7            7.8             0.150         0.34
5495   5495        5            6.6             0.410         0.31
5496   5496        6            7.0             0.350         0.17

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0
1                2.4      0.067                 10.0                  42.0
2                2.0      0.057                 21.0                 138.0
3                6.0      0.046                 29.0                 108.0
5                9.7      0.032                 17.0                  50.0
...              ...        ...                  ...                   ...
5491             4.7      0.029                 34.0                 148.0
5492             1.3      0.029                 10.0                  64.0
5494             1.1      0.035                 31.0                  93.0
5495             1.6      0.042                 18.0                 101.0
5496             1.1      0.049                  7.0                 119.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
0     0.99432  3.44       0.44     10.2              0.148760     0.0
1     0.99690  3.19       0.59      9.5              0.413223     1.0
2     0.99176  3.05       0.52     10.9              0.338843     0.0
3     0.99390  3.26       0.50     10.8              0.264463     0.0
5     0.99320  3.08       0.66     12.0              0.181818     0.0
...       ...   ...        ...      ...                   ...     ...
5491  0.99165  3.36       0.49     12.3              0.256198     0.0
5492  0.99320  3.35       0.39     10.1              0.322314     0.0
5494  0.99096  3.07       0.72     11.3              0.330579     0.0
5495  0.99195  3.13       0.41     10.5              0.231405     0.0
5496  0.99297  3.13       0.36      9.7              0.264463     0.0

      x0_white
0          1.0
1          0.0
2          1.0
3          1.0
5          1.0
...        ...
5491       1.0
5492       1.0
5494       1.0
5495       1.0
5496       1.0

[4397 rows x 16 columns]
#1번 교차검증 valid 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
4         4        6            7.8              0.40         0.26
12       12        7            7.3              0.33         0.40
14       14        5           12.5              0.38         0.60
15       15        5            7.8              0.49         0.49
29       29        4            7.6              0.26         0.36
...     ...      ...            ...               ...          ...
5459   5459        6            6.2              0.24         0.27
5475   5475        6            7.4              0.28         0.30
5479   5479        6            7.6              0.29         0.49
5486   5486        5            6.6              0.28         0.41
5493   5493        6            6.3              0.18         0.36

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
4               9.50      0.059                 32.0                 178.0
12              6.85      0.038                 32.0                 138.0
14              2.60      0.081                 31.0                  72.0
15              7.00      0.043                 29.0                 149.0
29              1.60      0.032                  6.0                 106.0
...              ...        ...                  ...                   ...
5459           16.80      0.040                 48.0                 129.0
5475            5.30      0.054                 44.0                 161.0
5479            2.70      0.092                 25.0                  60.0
5486            7.00      0.046                 59.0                 194.0
5493            1.20      0.034                 26.0                 111.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
4     0.99550  3.04       0.43     10.9              0.330579     0.0
12    0.99200  3.03       0.30     11.9              0.289256     0.0
14    0.99960  3.10       0.73     10.5              0.719008     1.0
15    0.99520  3.21       0.33     10.0              0.330579     0.0
29    0.99300  3.15       0.40     10.4              0.314050     0.0
...       ...   ...        ...      ...                   ...     ...
5459  0.99691  3.23       0.38     10.5              0.198347     0.0
5475  0.99410  3.12       0.48     10.3              0.297521     0.0
5479  0.99710  3.31       0.61     10.1              0.314050     1.0
5486  0.99558  3.14       0.48      9.4              0.231405     0.0
5493  0.99074  3.16       0.51     11.0              0.206612     0.0

      x0_white
4          1.0
12         1.0
14         0.0
15         1.0
29         1.0
...        ...
5459       1.0
5475       1.0
5479       0.0
5486       1.0
5493       1.0

[1100 rows x 16 columns]
#2번 교차검증 train 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
0         0        5            5.6             0.695         0.06
2         2        5            7.9             0.210         0.39
3         3        6            7.0             0.210         0.31
4         4        6            7.8             0.400         0.26
5         5        6            6.0             0.190         0.37
...     ...      ...            ...               ...          ...
5492   5492        5            7.7             0.150         0.29
5493   5493        6            6.3             0.180         0.36
5494   5494        7            7.8             0.150         0.34
5495   5495        5            6.6             0.410         0.31
5496   5496        6            7.0             0.350         0.17

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0
2                2.0      0.057                 21.0                 138.0
3                6.0      0.046                 29.0                 108.0
4                9.5      0.059                 32.0                 178.0
5                9.7      0.032                 17.0                  50.0
...              ...        ...                  ...                   ...
5492             1.3      0.029                 10.0                  64.0
5493             1.2      0.034                 26.0                 111.0
5494             1.1      0.035                 31.0                  93.0
5495             1.6      0.042                 18.0                 101.0
5496             1.1      0.049                  7.0                 119.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
0     0.99432  3.44       0.44     10.2              0.148760     0.0
2     0.99176  3.05       0.52     10.9              0.338843     0.0
3     0.99390  3.26       0.50     10.8              0.264463     0.0
4     0.99550  3.04       0.43     10.9              0.330579     0.0
5     0.99320  3.08       0.66     12.0              0.181818     0.0
...       ...   ...        ...      ...                   ...     ...
5492  0.99320  3.35       0.39     10.1              0.322314     0.0
5493  0.99074  3.16       0.51     11.0              0.206612     0.0
5494  0.99096  3.07       0.72     11.3              0.330579     0.0
5495  0.99195  3.13       0.41     10.5              0.231405     0.0
5496  0.99297  3.13       0.36      9.7              0.264463     0.0

      x0_white
0          1.0
2          1.0
3          1.0
4          1.0
5          1.0
...        ...
5492       1.0
5493       1.0
5494       1.0
5495       1.0
5496       1.0

[4397 rows x 16 columns]
#2번 교차검증 valid 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
1         1        5            8.8             0.610         0.14
9         9        5            6.8             0.390         0.35
22       22        6            7.1             0.210         0.33
23       23        6            7.7             0.715         0.01
32       32        6            6.8             0.270         0.30
...     ...      ...            ...               ...          ...
5456   5456        7            5.9             0.170         0.29
5457   5457        5            7.4             0.610         0.01
5472   5472        6            9.4             0.330         0.59
5478   5478        8            6.5             0.130         0.37
5490   5490        6           11.1             0.450         0.73

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
1                2.4      0.067                 10.0                  42.0
9               11.6      0.044                 57.0                 220.0
22               1.2      0.039                 34.0                  97.0
23               2.1      0.064                 31.0                  43.0
32              13.0      0.047                 69.0                 160.0
...              ...        ...                  ...                   ...
5456             3.1      0.030                 32.0                 123.0
5457             2.0      0.074                 13.0                  38.0
5472             2.8      0.079                  9.0                  30.0
5478             1.0      0.036                 48.0                 114.0
5490             3.2      0.066                  6.0                  22.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
1     0.99690  3.19       0.59      9.5              0.413223     1.0
9     0.99775  3.07       0.53      9.3              0.247934     0.0
22    0.99112  3.11       0.75     11.2              0.272727     0.0
23    0.99371  3.41       0.57     11.8              0.322314     1.0
32    0.99705  3.16       0.50      9.6              0.247934     0.0
...       ...   ...        ...      ...                   ...     ...
5456  0.98913  3.41       0.33     13.7              0.173554     0.0
5457  0.99748  3.48       0.65      9.8              0.297521     1.0
5472  0.99760  3.12       0.54     12.0              0.462810     1.0
5478  0.99110  3.41       0.51     11.5              0.223140     0.0
5490  0.99860  3.17       0.66     11.2              0.603306     1.0

      x0_white
1          0.0
9          1.0
22         1.0
23         0.0
32         1.0
...        ...
5456       1.0
5457       0.0
5472       0.0
5478       1.0
5490       0.0

[1100 rows x 16 columns]
#3번 교차검증 train 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
0         0        5            5.6             0.695         0.06
1         1        5            8.8             0.610         0.14
4         4        6            7.8             0.400         0.26
7         7        6            7.1             0.380         0.42
8         8        5            6.8             0.240         0.31
...     ...      ...            ...               ...          ...
5490   5490        6           11.1             0.450         0.73
5491   5491        7            6.9             0.340         0.30
5493   5493        6            6.3             0.180         0.36
5494   5494        7            7.8             0.150         0.34
5496   5496        6            7.0             0.350         0.17

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0
1                2.4      0.067                 10.0                  42.0
4                9.5      0.059                 32.0                 178.0
7               11.8      0.041                 32.0                 193.0
8               18.3      0.046                 40.0                 142.0
...              ...        ...                  ...                   ...
5490             3.2      0.066                  6.0                  22.0
5491             4.7      0.029                 34.0                 148.0
5493             1.2      0.034                 26.0                 111.0
5494             1.1      0.035                 31.0                  93.0
5496             1.1      0.049                  7.0                 119.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
0     0.99432  3.44       0.44     10.2              0.148760     0.0
1     0.99690  3.19       0.59      9.5              0.413223     1.0
4     0.99550  3.04       0.43     10.9              0.330579     0.0
7     0.99624  3.04       0.49     10.0              0.272727     0.0
8     1.00000  3.30       0.41      8.7              0.247934     0.0
...       ...   ...        ...      ...                   ...     ...
5490  0.99860  3.17       0.66     11.2              0.603306     1.0
5491  0.99165  3.36       0.49     12.3              0.256198     0.0
5493  0.99074  3.16       0.51     11.0              0.206612     0.0
5494  0.99096  3.07       0.72     11.3              0.330579     0.0
5496  0.99297  3.13       0.36      9.7              0.264463     0.0

      x0_white
0          1.0
1          0.0
4          1.0
7          1.0
8          1.0
...        ...
5490       0.0
5491       1.0
5493       1.0
5494       1.0
5496       1.0

[4398 rows x 16 columns]
#3번 교차검증 valid 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
2         2        5            7.9             0.210         0.39
3         3        6            7.0             0.210         0.31
5         5        6            6.0             0.190         0.37
6         6        5            6.1             0.220         0.49
10       10        6            8.0             0.180         0.37
...     ...      ...            ...               ...          ...
5481   5481        7            5.4             0.835         0.08
5484   5484        5            6.8             0.260         0.29
5487   5487        5            7.3             0.590         0.26
5492   5492        5            7.7             0.150         0.29
5495   5495        5            6.6             0.410         0.31

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
2               2.00      0.057                 21.0                 138.0
3               6.00      0.046                 29.0                 108.0
5               9.70      0.032                 17.0                  50.0
6               1.50      0.051                 18.0                  87.0
10              0.90      0.049                 36.0                 109.0
...              ...        ...                  ...                   ...
5481            1.20      0.046                 13.0                  93.0
5484           16.95      0.056                 48.0                 179.0
5487            7.20      0.070                 35.0                 121.0
5492            1.30      0.029                 10.0                  64.0
5495            1.60      0.042                 18.0                 101.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
2     0.99176  3.05       0.52     10.9              0.338843     0.0
3     0.99390  3.26       0.50     10.8              0.264463     0.0
5     0.99320  3.08       0.66     12.0              0.181818     0.0
6     0.99280  3.30       0.46      9.6              0.190083     0.0
10    0.99007  2.89       0.44     12.7              0.347107     1.0
...       ...   ...        ...      ...                   ...     ...
5481  0.99240  3.57       0.85     13.0              0.132231     1.0
5484  0.99980  3.45       0.40      9.6              0.247934     0.0
5487  0.99810  3.37       0.49      9.4              0.289256     1.0
5492  0.99320  3.35       0.39     10.1              0.322314     0.0
5495  0.99195  3.13       0.41     10.5              0.231405     0.0

      x0_white
2          1.0
3          1.0
5          1.0
6          1.0
10         0.0
...        ...
5481       0.0
5484       1.0
5487       0.0
5492       1.0
5495       1.0

[1099 rows x 16 columns]
#4번 교차검증 train 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
0         0        5            5.6             0.695         0.06
1         1        5            8.8             0.610         0.14
2         2        5            7.9             0.210         0.39
3         3        6            7.0             0.210         0.31
4         4        6            7.8             0.400         0.26
...     ...      ...            ...               ...          ...
5491   5491        7            6.9             0.340         0.30
5492   5492        5            7.7             0.150         0.29
5493   5493        6            6.3             0.180         0.36
5494   5494        7            7.8             0.150         0.34
5495   5495        5            6.6             0.410         0.31

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0
1                2.4      0.067                 10.0                  42.0
2                2.0      0.057                 21.0                 138.0
3                6.0      0.046                 29.0                 108.0
4                9.5      0.059                 32.0                 178.0
...              ...        ...                  ...                   ...
5491             4.7      0.029                 34.0                 148.0
5492             1.3      0.029                 10.0                  64.0
5493             1.2      0.034                 26.0                 111.0
5494             1.1      0.035                 31.0                  93.0
5495             1.6      0.042                 18.0                 101.0

      density    pH  sulphates  alcohol  Scaled fixed acidity  x0_red  \
0     0.99432  3.44       0.44     10.2              0.148760     0.0
1     0.99690  3.19       0.59      9.5              0.413223     1.0
2     0.99176  3.05       0.52     10.9              0.338843     0.0
3     0.99390  3.26       0.50     10.8              0.264463     0.0
4     0.99550  3.04       0.43     10.9              0.330579     0.0
...       ...   ...        ...      ...                   ...     ...
5491  0.99165  3.36       0.49     12.3              0.256198     0.0
5492  0.99320  3.35       0.39     10.1              0.322314     0.0
5493  0.99074  3.16       0.51     11.0              0.206612     0.0
5494  0.99096  3.07       0.72     11.3              0.330579     0.0
5495  0.99195  3.13       0.41     10.5              0.231405     0.0

      x0_white
0          1.0
1          0.0
2          1.0
3          1.0
4          1.0
...        ...
5491       1.0
5492       1.0
5493       1.0
5494       1.0
5495       1.0

[4398 rows x 16 columns]
#4번 교차검증 valid 데이터:       index  quality  fixed acidity  volatile acidity  citric acid  \
8         8        5            6.8              0.24         0.31
13       13        5            7.1              0.31         0.17
18       18        6            8.2              0.23         0.40
19       19        6            6.8              0.31         0.25
20       20        5            7.6              0.31         0.26
...     ...      ...            ...               ...          ...